/*
 * This source file was generated by the Gradle 'init' task
 */
package com.goriant.oauth;

public class Main {
    public static void main(String[] args) {
        // no need implement for now
    }
}
